[theme]
base="dark"
primaryColor="#FFD700"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"
font="sans serif"

[server]
headless = false #ui de dev


[ui]
hideSidebarNav = true